# Generated by Django 5.0.14 on 2025-11-14 17:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='The endpoint URL to send webhook POST requests to', max_length=500, validators=[django.core.validators.URLValidator()])),
                ('event_type', models.CharField(choices=[('product.created', 'Product Created'), ('product.updated', 'Product Updated'), ('product.deleted', 'Product Deleted'), ('product.bulk_deleted', 'Products Bulk Deleted'), ('upload.started', 'Upload Started'), ('upload.completed', 'Upload Completed'), ('upload.failed', 'Upload Failed')], db_index=True, help_text='The type of event that triggers this webhook', max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this webhook is active')),
                ('secret', models.CharField(blank=True, help_text='Secret key for HMAC signature verification', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('total_triggers', models.IntegerField(default=0)),
                ('successful_triggers', models.IntegerField(default=0)),
                ('failed_triggers', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Webhook',
                'verbose_name_plural': 'Webhooks',
                'db_table': 'webhooks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'is_active'], name='idx_webhook_event_active'), models.Index(fields=['-created_at'], name='idx_webhook_created')],
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, default='')),
                ('response_time', models.FloatField(blank=True, help_text='Response time in seconds', null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('is_successful', models.BooleanField(db_index=True, default=False)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='webhooks.webhook')),
            ],
            options={
                'verbose_name': 'Webhook Log',
                'verbose_name_plural': 'Webhook Logs',
                'db_table': 'webhook_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='idx_webhook_log_created'), models.Index(fields=['is_successful'], name='idx_webhook_log_success'), models.Index(fields=['event_type'], name='idx_webhook_log_event')],
            },
        ),
    ]
