# Generated by Django 5.0.14 on 2025-11-14 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sku', models.CharField(db_index=True, max_length=255)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('bulk_delete', 'Bulk Delete'), ('import', 'Import')], db_index=True, max_length=20)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('user', models.CharField(default='system', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='idx_audit_timestamp'), models.Index(fields=['product_sku'], name='idx_audit_sku'), models.Index(fields=['action'], name='idx_audit_action')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Stock Keeping Unit (SKU) - case insensitive unique identifier', max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('sku_lower', models.CharField(db_index=True, editable=False, help_text='Lowercase version of SKU for case-insensitive uniqueness', max_length=255, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sku_lower'], name='idx_sku_lower'), models.Index(fields=['is_active'], name='idx_is_active'), models.Index(fields=['-created_at'], name='idx_created_at'), models.Index(fields=['name'], name='idx_name')],
            },
        ),
        migrations.CreateModel(
            name='UploadJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.FileField(max_length=500, upload_to='uploads/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('total_rows', models.IntegerField(default=0)),
                ('processed_rows', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('created_count', models.IntegerField(default=0)),
                ('updated_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('error_details', models.JSONField(blank=True, default=list, null=True)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Upload Job',
                'verbose_name_plural': 'Upload Jobs',
                'db_table': 'upload_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='idx_upload_created'), models.Index(fields=['status'], name='idx_upload_status')],
            },
        ),
    ]
